server:
  port: 8888

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://mysql-server:3306/db_mall_sms?serverTimezone=UTC&useSSL=false&allowMultiQueries=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8333
  application:
    name: coupon-service

# MapperScan
# sql映射文件位置
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

  # 服务追踪发现
  zipkin:
    base-url: http://zipkin-server:9411/
    # 关闭自己的服务发现功能
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
    redis:
      enabled: false
# 开启debug日志
log:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug